server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myproducts
    username: ${POSTGRES_USERNAME_LOCAL}
    password: ${POSTGRES_PASSWORD_LOCAL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
